name: Node.js CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]
            fail-fast: true
        steps:
            - name: Copy Environment Variables
              run: |
                  touch .env
                  echo "FIREBASE_API_KEY=${{secrets.FIREBASE_API_KEY}}" >> .env
            - name: Use Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{matrix.node-version}}
            - name: npm install & build
              run: |
                  npm install -g yarn
                  yarn
                  yarn build:gh-pages
